server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    consul:
      discovery:
        preferIpAddress: true
        enabled: true
        register: true
        service-name: config-service
        health-check-interval: 10s
        health-check-timeout: 20s
        heartbeat:
          enabled: true
        ip-address: 127.0.0.1
        port: ${server.port}
        lifecycle:
          enabled: true
        scheme: http
        prefer-agent-address: false
        register-health-check: true
        tags: master
        query-passing: true
      retry:
        initial-interval: 1000
        max-attempts: 4
        max-interval: 1000
      host: 127.0.0.1
      port: 8500

---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lixichongAAA/config-repo.git
          searchPaths: ${APP_LOCATE:dev}
#          username: user
#          password: pwd
---
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: '*'